# Generated by Django 6.1 on 2026-09-05 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semesters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=200)),
                ('credits', models.IntegerField(default=3)),
                ('subject_type', models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical'), ('Project', 'Project')], max_length=20)),
                ('maximum_mark', models.IntegerField(default=100)),
                ('pass_mark', models.IntegerField(default=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semesters.semester')),
            ],
        ),
    ]
