# Generated by Django 6.1 on 2026-09-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('university_type', models.CharField(choices=[('State', 'State'), ('Central', 'Central'), ('Autonomous', 'Autonomous'), ('Deemed', 'Deemed'), ('Private', 'Private')], max_length=20)),
                ('total_semesters', models.IntegerField()),
                ('cgpa_scale', models.CharField(choices=[('10', '10 Point'), ('4', '4 Point')], max_length=5)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
